--- #YAML:1.0
name: URI-Title
version: 0.3
author:
  - ~
abstract: |-
  get the titles of things on the web in a sensible way
license: perl
requires:
  LWP: 0.01
  Test::More: 0.01
provides:
  URI::Title:
    file: lib/URI/Title.pm
    version: 0.3
generated_by: Module::Build version 0.24
