---
abstract: 'get the titles of things on the web in a sensible way'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  IO::Socket: '0'
  Test::More: '0.88'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: URI-Title
requires:
  Carp: '0'
  Encode: '0'
  Exporter: '0'
  File::Temp: '0'
  File::Type: '0.22'
  HTML::Entities: '0'
  HTML::Parser: '3.45'
  HTTP::Request: '0'
  HTTP::Response: '0'
  Image::Size: '0'
  LWP::UserAgent: '0'
  MP3::Info: '0'
  Module::Pluggable: '1.2'
  base: '0'
  perl: '5.006'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=URI-Title
  repository: http://github.com/book/URI-Title.git
version: '1.900'
